-- Farm2Pot seed data — generated from app/data/menu.ts
-- Run this AFTER schema.sql, in the Supabase SQL Editor

-- Categories
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('soups', 'Soups', 'Food', null, 2050, 1650, 0);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('swallows', 'Swallows', 'Food', 2500, null, null, 1);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('proteins', 'Proteins', 'Food', null, null, null, 2);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('rice', 'Rice', 'Food', null, null, null, 3);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('fries', 'Fries', 'Food', null, null, null, 4);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('grills', 'Grills', 'Food', null, null, null, 5);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('shawarma', 'Shawarma', 'Food', null, null, null, 6);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('pasta', 'Pasta', 'Food', null, null, null, 7);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('snacks', 'Snacks', 'Food', null, null, null, 8);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('pepper-soups', 'Pepper Soups', 'Food', null, null, null, 9);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('ramen-pepper-soup', 'Ramen Pepper Soup', 'Food', null, null, null, 10);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('dessert', 'Dessert', 'Food', null, null, null, 11);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('beers', 'Beers & Cider', 'Drinks', 2000, null, null, 12);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('soft-drinks', 'Soft Drinks', 'Drinks', 1000, null, null, 13);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('water', 'Water', 'Drinks', null, null, null, 14);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('fresh-juice', 'Fresh Juice', 'Drinks', 4000, null, null, 15);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('pack-juice', 'Pack Juice', 'Drinks', 4500, null, null, 16);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('yogurt', 'Yogurt', 'Drinks', 6000, null, null, 17);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('cocktails', 'Cocktails', 'Drinks', null, null, null, 18);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('milkshakes', 'Milkshakes', 'Drinks', null, null, null, 19);
insert into categories (id, name, group_name, flat_price, big_price, small_price, sort_order) values ('shisha', 'Shisha', 'Experience', 10000, null, null, 20);

-- Menu items
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Egusi Soup', null, '/menu-images/egusi-soup.jpg', 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Ogbono Soup', null, '/menu-images/ogbono-soup.jpg', 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Okro Soup', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Fisherman Soup', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Oha Soup', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Afia Efere (White Soup)', null, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Efo Soup', null, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Edikang Ikong Soup', null, '/menu-images/edikang-ikong.jpg', 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('soups', 'Afang Soup', null, '/menu-images/afang-soup.jpg', 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('swallows', 'Eba', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('swallows', 'Semovita', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('swallows', 'Poondo Yam', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('swallows', 'Wheat', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Turkey', 8000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Chicken', 7000, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Goat Meat', 7000, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Catfish', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Croaker', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('proteins', 'Beef', null, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('rice', 'Jollof Rice', null, '/menu-images/jollof-rice.jpg', 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('rice', 'Fried Rice', null, '/menu-images/fried-rice.jpg', 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('rice', 'Coconut Rice', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('rice', 'Wheat Rice + Stew', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('rice', 'Noodles + Egg', 4000, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('fries', 'Potatoes', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('fries', 'Plantain', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('fries', 'Yam Chips', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Grilled Chicken', 7000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Grilled Turkey', 8000, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Suya', 2000, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Tozo', 2000, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Ram Suya (1kg)', 30000, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Ram Suya (half kg)', 15000, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Shaki', 1500, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Guinea Fowl', 13000, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('grills', 'Burger', null, '/menu-images/burger.jpg', 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Beef Shawarma', 5000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Beef Shawarma (Double Sausage)', 7000, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Chicken Shawarma', 5000, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Chicken Shawarma (Double Sausage)', 7000, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Suya Shawarma', 8000, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Ram Suya Shawarma', 11500, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Asun Shawarma', 11500, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Special Shawarma', 15000, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Cheese Chicken Shawarma', 15000, null, 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Cheese Beef Shawarma', 11500, null, 9);
insert into menu_items (category_id, name, price, image, sort_order) values ('shawarma', 'Croaker Fish Shawarma', 25500, null, 10);
insert into menu_items (category_id, name, price, image, sort_order) values ('pasta', 'Spaghetti', null, '/menu-images/spaghetti.jpg', 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('snacks', 'Egg Roll', null, '/menu-images/egg-roll.jpg', 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('pepper-soups', 'Goat Meat Pepper Soup', 11500, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('pepper-soups', 'Beef Pepper Soup', 11500, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('pepper-soups', 'Chicken Pepper Soup', 11500, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('pepper-soups', 'Turkey Pepper Soup', 16500, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('pepper-soups', 'Catfish Pepper Soup', 25500, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Chicken Ramen Pepper Soup', 13500, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Beef Ramen Pepper Soup', 13500, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Goat Meat Ramen Pepper Soup', 15500, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Turkey Meat Ramen Pepper Soup', 16500, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Catfish Ramen Pepper Soup', 15500, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Seafood Ramen Pepper Soup', 20000, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('ramen-pepper-soup', 'Farm2Pot Special Ramen Pepper Soup', 22000, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('dessert', 'Parfait', 9000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Heineken', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Trophy', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Star', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Star Radler', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Gulder', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Goldberg', null, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Life', null, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', '33 Export', null, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Budweiser', null, null, 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Small Stout', null, null, 9);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Desperados', null, null, 10);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Smirnoff Ice', null, null, 11);
insert into menu_items (category_id, name, price, image, sort_order) values ('beers', 'Origin Bitters', null, null, 12);
insert into menu_items (category_id, name, price, image, sort_order) values ('soft-drinks', 'Coca-Cola', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('soft-drinks', 'Fanta', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('soft-drinks', 'Sprite', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('soft-drinks', 'Schweppes', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('soft-drinks', 'Malt', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('water', 'Bottled Water', 700, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Fresh Orange Juice', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Pineapple & Ginger', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Fresh Watermelon', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Pineapple & Orange', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Sugarcane & Ginger', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Zobo', null, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Pineapple, Carrot & Ginger', null, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('fresh-juice', 'Tigernut Drink', null, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('pack-juice', 'Five Alive', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('pack-juice', 'Berry Blast', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('pack-juice', 'Chivita', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('pack-juice', 'Hollandia', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('pack-juice', 'Active', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('yogurt', 'Yogofura', null, '/menu-images/yogofura.jpg', 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('yogurt', 'Plain Yogurt', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('yogurt', 'Yogurt with Chia Seed', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('yogurt', 'Banana Yogurt', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Mojito', 8000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Strawberry Mojito', 9000, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Pineapple Mojito', 9000, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Long Island Iced Tea', 12000, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Sex on the Beach', 10000, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Tequila Sunrise', 9000, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Piña Colada', 10000, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Margarita', 10000, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('cocktails', 'Chapman', 7000, null, 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Vanilla', 9000, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Chocolate', 9000, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Strawberry', 9000, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Oreo', 10000, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Lotus Biscoff', 11000, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Caramel', 10000, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Banana', 9000, null, 6);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Nutella', 10000, null, 7);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Peanut Butter', 11500, null, 8);
insert into menu_items (category_id, name, price, image, sort_order) values ('milkshakes', 'Vanilla & Strawberry Swirl', 10000, null, 9);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Double Apple', null, null, 0);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Mint', null, null, 1);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Grape', null, null, 2);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Watermelon', null, null, 3);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Blueberry', null, null, 4);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Peach', null, null, 5);
insert into menu_items (category_id, name, price, image, sort_order) values ('shisha', 'Lemon & Mint', null, null, 6);
